service: serverx-serverless

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  app:
    handler: server.aws
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
